dist: jammy

addons:
  apt:
    sources:
      - sourceline: 'deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'
    packages:
      - docker

language: python

python:
  - '3.11'

install:
  - pip install -r requirements.txt

script:
  - pytest
