"""User password update

Revision ID: e6f3053e9f4e
Revises: 65eb3bc18ce2
Create Date: 2023-09-30 01:36:25.546705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f3053e9f4e'
down_revision = '65eb3bc18ce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=94),
               type_=sa.VARCHAR(length=102),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=102),
               type_=sa.VARCHAR(length=94),
               existing_nullable=False)

    # ### end Alembic commands ###
