name: Python CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      docker:
        image: docker:stable
        options: --privileged

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

<<<<<<< HEAD
=======
      - name: Install Docker (official script)
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          sudo usermod -aG docker $USER

>>>>>>> d3b339522548534ef8567de331fbaac11e8855f6
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
