name: Python CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-22.04

    env:
      DOCKER_HOST: unix:///var/run/docker.sock
      PYWOCHAT_SECRET_KEY: ${{ secrets.PYWOCHAT_SECRET_KEY }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Docker info
        run: |
          docker version
          docker info
          echo "DOCKER_HOST=$DOCKER_HOST"

      - name: Run tests
        run: pytest
